spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/test
    username: root
    password: 123456

  thymeleaf:
    cache: false

PSP:
  toss:
    secretKey: test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6
    url: https://api.tosspayments.com