spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/test
    username: root
    password: 123456

  thymeleaf:
    cache: false

  cloud:
    stream:
      kafka:
        binder:
          brokers: "bootstrap.servers data 입력"
          configuration:
            security:
              protocol: SASL_SSL
            sasl:
              mechanism: PLAIN
              jaas:
                config: "sasl.jaas.config data 입력"
            client:
              dns:
                lookup: use_all_dns_ips

          required-acks: all
          auto-create-topics: false

      bindings:
        consume-in-0:
          destination: payment
          group: payment-service

management:
  endpoints:
    web:
      exposure:
        include: bindings


logging:
  level:
    org:
      springframework:
        web: DEBUG
        r2dbc: DEBUG
        transaction: DEBUG


PSP:
  toss:
    secretKey: test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6
    url: https://api.tosspayments.com